// Code generated by protoc-gen-go. DO NOT EDIT.
// source: executionvenue.proto

package executionvenue

import (
	"github.com/ettec/otp-common/model"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAndRouteOrderParams struct {
	OrderSide            model.Side       `protobuf:"varint,1,opt,name=orderSide,proto3,enum=model.Side" json:"orderSide,omitempty"`
	Quantity             *model.Decimal64 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                *model.Decimal64 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	ListingId            int32      `protobuf:"varint,4,opt,name=listingId,proto3" json:"listingId,omitempty"`
	Destination          string     `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	OriginatorId         string     `protobuf:"bytes,6,opt,name=originatorId,proto3" json:"originatorId,omitempty"`
	OriginatorRef        string     `protobuf:"bytes,7,opt,name=originatorRef,proto3" json:"originatorRef,omitempty"`
	RootOriginatorId     string     `protobuf:"bytes,8,opt,name=rootOriginatorId,proto3" json:"rootOriginatorId,omitempty"`
	RootOriginatorRef    string     `protobuf:"bytes,9,opt,name=rootOriginatorRef,proto3" json:"rootOriginatorRef,omitempty"`
	ExecParametersJson   string     `protobuf:"bytes,10,opt,name=execParametersJson,proto3" json:"execParametersJson,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateAndRouteOrderParams) Reset()         { *m = CreateAndRouteOrderParams{} }
func (m *CreateAndRouteOrderParams) String() string { return proto.CompactTextString(m) }
func (*CreateAndRouteOrderParams) ProtoMessage()    {}
func (*CreateAndRouteOrderParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_30da1a85cda8249c, []int{0}
}

func (m *CreateAndRouteOrderParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAndRouteOrderParams.Unmarshal(m, b)
}
func (m *CreateAndRouteOrderParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAndRouteOrderParams.Marshal(b, m, deterministic)
}
func (m *CreateAndRouteOrderParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAndRouteOrderParams.Merge(m, src)
}
func (m *CreateAndRouteOrderParams) XXX_Size() int {
	return xxx_messageInfo_CreateAndRouteOrderParams.Size(m)
}
func (m *CreateAndRouteOrderParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAndRouteOrderParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAndRouteOrderParams proto.InternalMessageInfo

func (m *CreateAndRouteOrderParams) GetOrderSide() model.Side {
	if m != nil {
		return m.OrderSide
	}
	return model.Side_BUY
}

func (m *CreateAndRouteOrderParams) GetQuantity() *model.Decimal64 {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *CreateAndRouteOrderParams) GetPrice() *model.Decimal64 {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *CreateAndRouteOrderParams) GetListingId() int32 {
	if m != nil {
		return m.ListingId
	}
	return 0
}

func (m *CreateAndRouteOrderParams) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *CreateAndRouteOrderParams) GetOriginatorId() string {
	if m != nil {
		return m.OriginatorId
	}
	return ""
}

func (m *CreateAndRouteOrderParams) GetOriginatorRef() string {
	if m != nil {
		return m.OriginatorRef
	}
	return ""
}

func (m *CreateAndRouteOrderParams) GetRootOriginatorId() string {
	if m != nil {
		return m.RootOriginatorId
	}
	return ""
}

func (m *CreateAndRouteOrderParams) GetRootOriginatorRef() string {
	if m != nil {
		return m.RootOriginatorRef
	}
	return ""
}

func (m *CreateAndRouteOrderParams) GetExecParametersJson() string {
	if m != nil {
		return m.ExecParametersJson
	}
	return ""
}

type OrderId struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderId) Reset()         { *m = OrderId{} }
func (m *OrderId) String() string { return proto.CompactTextString(m) }
func (*OrderId) ProtoMessage()    {}
func (*OrderId) Descriptor() ([]byte, []int) {
	return fileDescriptor_30da1a85cda8249c, []int{1}
}

func (m *OrderId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderId.Unmarshal(m, b)
}
func (m *OrderId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderId.Marshal(b, m, deterministic)
}
func (m *OrderId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderId.Merge(m, src)
}
func (m *OrderId) XXX_Size() int {
	return xxx_messageInfo_OrderId.Size(m)
}
func (m *OrderId) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderId.DiscardUnknown(m)
}

var xxx_messageInfo_OrderId proto.InternalMessageInfo

func (m *OrderId) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type ExecParamsMetaDataJson struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecParamsMetaDataJson) Reset()         { *m = ExecParamsMetaDataJson{} }
func (m *ExecParamsMetaDataJson) String() string { return proto.CompactTextString(m) }
func (*ExecParamsMetaDataJson) ProtoMessage()    {}
func (*ExecParamsMetaDataJson) Descriptor() ([]byte, []int) {
	return fileDescriptor_30da1a85cda8249c, []int{2}
}

func (m *ExecParamsMetaDataJson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecParamsMetaDataJson.Unmarshal(m, b)
}
func (m *ExecParamsMetaDataJson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecParamsMetaDataJson.Marshal(b, m, deterministic)
}
func (m *ExecParamsMetaDataJson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecParamsMetaDataJson.Merge(m, src)
}
func (m *ExecParamsMetaDataJson) XXX_Size() int {
	return xxx_messageInfo_ExecParamsMetaDataJson.Size(m)
}
func (m *ExecParamsMetaDataJson) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecParamsMetaDataJson.DiscardUnknown(m)
}

var xxx_messageInfo_ExecParamsMetaDataJson proto.InternalMessageInfo

func (m *ExecParamsMetaDataJson) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type CancelOrderParams struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Listing              *model.Listing `protobuf:"bytes,2,opt,name=listing,proto3" json:"listing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderParams) Reset()         { *m = CancelOrderParams{} }
func (m *CancelOrderParams) String() string { return proto.CompactTextString(m) }
func (*CancelOrderParams) ProtoMessage()    {}
func (*CancelOrderParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_30da1a85cda8249c, []int{3}
}

func (m *CancelOrderParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderParams.Unmarshal(m, b)
}
func (m *CancelOrderParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderParams.Marshal(b, m, deterministic)
}
func (m *CancelOrderParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderParams.Merge(m, src)
}
func (m *CancelOrderParams) XXX_Size() int {
	return xxx_messageInfo_CancelOrderParams.Size(m)
}
func (m *CancelOrderParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderParams.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderParams proto.InternalMessageInfo

func (m *CancelOrderParams) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *CancelOrderParams) GetListing() *model.Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

type ModifyOrderParams struct {
	OrderId              string     `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Listing              *model.Listing   `protobuf:"bytes,2,opt,name=listing,proto3" json:"listing,omitempty"`
	Quantity             *model.Decimal64 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                *model.Decimal64 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ModifyOrderParams) Reset()         { *m = ModifyOrderParams{} }
func (m *ModifyOrderParams) String() string { return proto.CompactTextString(m) }
func (*ModifyOrderParams) ProtoMessage()    {}
func (*ModifyOrderParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_30da1a85cda8249c, []int{4}
}

func (m *ModifyOrderParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyOrderParams.Unmarshal(m, b)
}
func (m *ModifyOrderParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyOrderParams.Marshal(b, m, deterministic)
}
func (m *ModifyOrderParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyOrderParams.Merge(m, src)
}
func (m *ModifyOrderParams) XXX_Size() int {
	return xxx_messageInfo_ModifyOrderParams.Size(m)
}
func (m *ModifyOrderParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyOrderParams.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyOrderParams proto.InternalMessageInfo

func (m *ModifyOrderParams) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ModifyOrderParams) GetListing() *model.Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

func (m *ModifyOrderParams) GetQuantity() *model.Decimal64 {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *ModifyOrderParams) GetPrice() *model.Decimal64 {
	if m != nil {
		return m.Price
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAndRouteOrderParams)(nil), "executionvenue.CreateAndRouteOrderParams")
	proto.RegisterType((*OrderId)(nil), "executionvenue.OrderId")
	proto.RegisterType((*ExecParamsMetaDataJson)(nil), "executionvenue.ExecParamsMetaDataJson")
	proto.RegisterType((*CancelOrderParams)(nil), "executionvenue.CancelOrderParams")
	proto.RegisterType((*ModifyOrderParams)(nil), "executionvenue.ModifyOrderParams")
}

func init() { proto.RegisterFile("executionvenue.proto", fileDescriptor_30da1a85cda8249c) }

var fileDescriptor_30da1a85cda8249c = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x9b, 0xa4, 0xa9, 0xc7, 0x6d, 0xd4, 0x0c, 0x08, 0x8c, 0x85, 0x90, 0x31, 0xa8, 0x72,
	0x51, 0xe4, 0x43, 0x40, 0x9c, 0x41, 0x6d, 0x84, 0x82, 0xa8, 0x8a, 0x8c, 0x04, 0x48, 0x9c, 0x16,
	0x7b, 0x5a, 0x19, 0xc5, 0xde, 0xb0, 0xde, 0x20, 0xf2, 0x51, 0x48, 0xfc, 0x07, 0x3f, 0x85, 0x76,
	0x6d, 0x27, 0x76, 0x9c, 0x20, 0x0e, 0xbd, 0xed, 0xbc, 0x79, 0xf3, 0xd6, 0x3b, 0x6f, 0xc6, 0x70,
	0x97, 0x7e, 0x52, 0xb4, 0x90, 0x09, 0xcf, 0x7e, 0x50, 0xb6, 0xa0, 0x60, 0x2e, 0xb8, 0xe4, 0x38,
	0x68, 0xa2, 0xce, 0xf1, 0x2c, 0xc9, 0x65, 0x92, 0xdd, 0x14, 0x69, 0xc7, 0xe2, 0x22, 0x26, 0x51,
	0x06, 0xc3, 0x94, 0xc7, 0x34, 0x8b, 0x78, 0x9a, 0xf2, 0xac, 0x80, 0xbc, 0xdf, 0x1d, 0x78, 0x70,
	0x2e, 0x88, 0x49, 0x7a, 0x9d, 0xc5, 0x21, 0x5f, 0x48, 0xba, 0x52, 0x05, 0xef, 0x99, 0x60, 0x69,
	0x8e, 0x67, 0x60, 0xea, 0xfa, 0x0f, 0x49, 0x4c, 0xb6, 0xe1, 0x1a, 0xfe, 0x60, 0x6c, 0x05, 0x5a,
	0x24, 0x50, 0x50, 0xb8, 0xce, 0xe2, 0x08, 0x0e, 0xbf, 0x2f, 0x58, 0x26, 0x13, 0xb9, 0xb4, 0xf7,
	0x5d, 0xc3, 0xb7, 0xc6, 0x27, 0x25, 0xf3, 0x82, 0xa2, 0x24, 0x65, 0xb3, 0x97, 0x2f, 0xc2, 0x15,
	0x03, 0x4f, 0xa1, 0x37, 0x17, 0x49, 0x44, 0x76, 0x67, 0x07, 0xb5, 0x48, 0xe3, 0x43, 0x30, 0xcb,
	0xf7, 0x4c, 0x63, 0xbb, 0xeb, 0x1a, 0x7e, 0x2f, 0x5c, 0x03, 0xe8, 0x82, 0x15, 0x93, 0x0a, 0x98,
	0x7a, 0xbf, 0xdd, 0x73, 0x0d, 0xdf, 0x0c, 0xeb, 0x10, 0x7a, 0x70, 0xc4, 0x45, 0x72, 0xa3, 0x42,
	0x2e, 0xa6, 0xb1, 0x7d, 0xa0, 0x29, 0x0d, 0x0c, 0x9f, 0xc2, 0xf1, 0x3a, 0x0e, 0xe9, 0xda, 0xee,
	0x6b, 0x52, 0x13, 0xc4, 0x67, 0x70, 0x22, 0x38, 0x97, 0x57, 0x75, 0xb5, 0x43, 0x4d, 0x6c, 0xe1,
	0x38, 0x82, 0x61, 0x13, 0x53, 0xaa, 0xa6, 0x26, 0xb7, 0x13, 0x18, 0x00, 0x2a, 0x0f, 0x75, 0xcb,
	0x49, 0x92, 0xc8, 0xdf, 0xe6, 0x3c, 0xb3, 0x41, 0xd3, 0xb7, 0x64, 0xbc, 0x27, 0xd0, 0xd7, 0x1e,
	0x4d, 0x63, 0xb4, 0xa1, 0xcf, 0x8b, 0xa3, 0x76, 0xc7, 0x0c, 0xab, 0xd0, 0x1b, 0xc1, 0xbd, 0x49,
	0x55, 0x9a, 0x5f, 0x92, 0x64, 0x17, 0x4c, 0x32, 0x55, 0x8e, 0x08, 0xdd, 0x6f, 0xea, 0x82, 0xa2,
	0x40, 0x9f, 0xbd, 0x4f, 0x30, 0x3c, 0x67, 0x59, 0x44, 0xb3, 0xba, 0xf9, 0x3b, 0xc5, 0xd1, 0x87,
	0x7e, 0x69, 0x42, 0x69, 0xf5, 0xa0, 0xf4, 0xef, 0x5d, 0x81, 0x86, 0x55, 0xda, 0xfb, 0x65, 0xc0,
	0xf0, 0x92, 0xc7, 0xc9, 0xf5, 0xf2, 0x96, 0x95, 0x1b, 0xf3, 0xd6, 0xf9, 0xff, 0x79, 0xeb, 0xfe,
	0x73, 0xde, 0xc6, 0x7f, 0xf6, 0x61, 0x30, 0xa9, 0x16, 0xea, 0xa3, 0x5a, 0x28, 0xfc, 0x02, 0x77,
	0xb6, 0x2c, 0x08, 0x9e, 0x05, 0x1b, 0xeb, 0xb8, 0x73, 0x8b, 0x9c, 0xfb, 0x9b, 0xd4, 0xd2, 0x3e,
	0x6f, 0x0f, 0x5f, 0x81, 0x55, 0x6b, 0x3c, 0x3e, 0x6e, 0x89, 0x6e, 0xba, 0xe2, 0x1c, 0x95, 0x9f,
	0x3e, 0x49, 0xe7, 0x72, 0x59, 0x28, 0xd4, 0x1a, 0xdc, 0x56, 0x68, 0x75, 0xbf, 0xa5, 0xf0, 0x19,
	0x1e, 0xbd, 0x21, 0xb9, 0x7a, 0xf5, 0x7a, 0xda, 0xaa, 0xb1, 0xc1, 0x46, 0x85, 0x73, 0xba, 0x79,
	0xc5, 0xf6, 0x41, 0xf3, 0xf6, 0xbe, 0x1e, 0xe8, 0x7f, 0xcc, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x74, 0x3a, 0x74, 0x4d, 0xba, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExecutionVenueClient is the client API for ExecutionVenue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecutionVenueClient interface {
	CreateAndRouteOrder(ctx context.Context, in *CreateAndRouteOrderParams, opts ...grpc.CallOption) (*OrderId, error)
	CancelOrder(ctx context.Context, in *CancelOrderParams, opts ...grpc.CallOption) (*model.Empty, error)
	ModifyOrder(ctx context.Context, in *ModifyOrderParams, opts ...grpc.CallOption) (*model.Empty, error)
	GetExecutionParametersMetaData(ctx context.Context, in *model.Empty, opts ...grpc.CallOption) (*ExecParamsMetaDataJson, error)
}

type executionVenueClient struct {
	cc *grpc.ClientConn
}

func NewExecutionVenueClient(cc *grpc.ClientConn) ExecutionVenueClient {
	return &executionVenueClient{cc}
}

func (c *executionVenueClient) CreateAndRouteOrder(ctx context.Context, in *CreateAndRouteOrderParams, opts ...grpc.CallOption) (*OrderId, error) {
	out := new(OrderId)
	err := c.cc.Invoke(ctx, "/executionvenue.ExecutionVenue/CreateAndRouteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionVenueClient) CancelOrder(ctx context.Context, in *CancelOrderParams, opts ...grpc.CallOption) (*model.Empty, error) {
	out := new(model.Empty)
	err := c.cc.Invoke(ctx, "/executionvenue.ExecutionVenue/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionVenueClient) ModifyOrder(ctx context.Context, in *ModifyOrderParams, opts ...grpc.CallOption) (*model.Empty, error) {
	out := new(model.Empty)
	err := c.cc.Invoke(ctx, "/executionvenue.ExecutionVenue/ModifyOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionVenueClient) GetExecutionParametersMetaData(ctx context.Context, in *model.Empty, opts ...grpc.CallOption) (*ExecParamsMetaDataJson, error) {
	out := new(ExecParamsMetaDataJson)
	err := c.cc.Invoke(ctx, "/executionvenue.ExecutionVenue/GetExecutionParametersMetaData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionVenueServer is the server API for ExecutionVenue service.
type ExecutionVenueServer interface {
	CreateAndRouteOrder(context.Context, *CreateAndRouteOrderParams) (*OrderId, error)
	CancelOrder(context.Context, *CancelOrderParams) (*model.Empty, error)
	ModifyOrder(context.Context, *ModifyOrderParams) (*model.Empty, error)
	GetExecutionParametersMetaData(context.Context, *model.Empty) (*ExecParamsMetaDataJson, error)
}

// UnimplementedExecutionVenueServer can be embedded to have forward compatible implementations.
type UnimplementedExecutionVenueServer struct {
}

func (*UnimplementedExecutionVenueServer) CreateAndRouteOrder(ctx context.Context, req *CreateAndRouteOrderParams) (*OrderId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAndRouteOrder not implemented")
}
func (*UnimplementedExecutionVenueServer) CancelOrder(ctx context.Context, req *CancelOrderParams) (*model.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (*UnimplementedExecutionVenueServer) ModifyOrder(ctx context.Context, req *ModifyOrderParams) (*model.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyOrder not implemented")
}
func (*UnimplementedExecutionVenueServer) GetExecutionParametersMetaData(ctx context.Context, req *model.Empty) (*ExecParamsMetaDataJson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionParametersMetaData not implemented")
}

func RegisterExecutionVenueServer(s *grpc.Server, srv ExecutionVenueServer) {
	s.RegisterService(&_ExecutionVenue_serviceDesc, srv)
}

func _ExecutionVenue_CreateAndRouteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAndRouteOrderParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionVenueServer).CreateAndRouteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/executionvenue.ExecutionVenue/CreateAndRouteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionVenueServer).CreateAndRouteOrder(ctx, req.(*CreateAndRouteOrderParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionVenue_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionVenueServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/executionvenue.ExecutionVenue/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionVenueServer).CancelOrder(ctx, req.(*CancelOrderParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionVenue_ModifyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyOrderParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionVenueServer).ModifyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/executionvenue.ExecutionVenue/ModifyOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionVenueServer).ModifyOrder(ctx, req.(*ModifyOrderParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionVenue_GetExecutionParametersMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionVenueServer).GetExecutionParametersMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/executionvenue.ExecutionVenue/GetExecutionParametersMetaData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionVenueServer).GetExecutionParametersMetaData(ctx, req.(*model.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecutionVenue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "executionvenue.ExecutionVenue",
	HandlerType: (*ExecutionVenueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAndRouteOrder",
			Handler:    _ExecutionVenue_CreateAndRouteOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _ExecutionVenue_CancelOrder_Handler,
		},
		{
			MethodName: "ModifyOrder",
			Handler:    _ExecutionVenue_ModifyOrder_Handler,
		},
		{
			MethodName: "GetExecutionParametersMetaData",
			Handler:    _ExecutionVenue_GetExecutionParametersMetaData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "executionvenue.proto",
}
